name: "Push events"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1'

permissions:
  contents: read
  packages: read

jobs:
  syndicate:
    name: "Post events"
    runs-on: ubuntu-latest

    steps:
    - name: "Check out repository"
      uses: actions/checkout@v3

    - name: Configure RubyGems credentials for GitHub Packages
      run: |
        mkdir -p ~/.gem
        
        cat > ~/.gem/credentials <<'EOF'
        ---
        :github: Bearer ${{ secrets.GITHUB_TOKEN }}
        rubygems.pkg.github.com: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
        EOF
        
        chmod 0600 ~/.gem/credentials

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: bundle exec ruby main.rb
      env:
        SYN_ENV: production
        TD_SLACK_WEBHOOK: ${{ secrets.TD_SLACK_WEBHOOK }}
        TBT_SLACK_WEBHOOK: ${{ secrets.TBT_SLACK_WEBHOOK }}
        TBUX_SLACK_WEBHOOK: ${{ secrets.TBUX_SLACK_WEBHOOK }}
